#### Train Config ####
model:
  name: BERT
  num_classes: 2
data:
  pad: 32
  train_path: ./path/to/data
  val_path: ./path/to/data
  train_batch_size: 100
  val_batch_size: 200
  skip_first: true
  delimiter: "\t"
optimizer:
  lr: 0.00003
  weight_decay: 0.0005
loss: FocalCE
#schedulers:
#  name: MultiStepLR
#  milestones: [6]
#  gamma: 0.1
num_steps: 8000
device: 0
log_steps: 100
val_steps: 200
#id: YYYY-MM-DD...HH.MM.SS
#ckpt_fold: runs

#### Test Config ####
# model:
#     name: BERT
#     num_classes: 2
# data:
#     pad: 32
#     skip_first: true
#     val_path: ./path/to/data
#     val_batch_size: 200
# device: 0
# id: YYYY-MM-DD...HH.MM.SS
# ckpt_fold: runs